"""empty message

Revision ID: 1abf46d5d364
Revises: a7c7c4cc3eb7
Create Date: 2025-04-09 12:34:10.967005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abf46d5d364'
down_revision = 'a7c7c4cc3eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # In your migration file
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(100), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('availability_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security_answer_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security_question_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security_answer_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security_question_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('security_answer_3', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_answer_3')
        batch_op.drop_column('security_question_3')
        batch_op.drop_column('security_answer_2')
        batch_op.drop_column('security_question_2')
        batch_op.drop_column('security_answer_1')
        batch_op.drop_column('security_question_1')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('availability_end')
        batch_op.drop_column('availability_start')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
