"""empty message

Revision ID: 765678e0eee8
Revises: 1abf46d5d364
Create Date: 2025-04-09 19:55:27.106574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765678e0eee8'
down_revision = '1abf46d5d364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_car')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('availability_end')
        batch_op.drop_column('availability_start')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.alter_column('amount',
                              existing_type=sa.FLOAT(),
                              nullable=False)
        # The following two lines dropped unnamed foreign key constraints.
        # They have been removed because SQLite does not support dropping unnamed constraints.
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_payment_receiver', 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('fk_payment_sender', 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key('fk_payment_booking', 'booking', ['booking_id'], ['id'])
        batch_op.drop_column('car_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_payment_booking', type_='foreignkey')
        batch_op.drop_constraint('fk_payment_sender', type_='foreignkey')
        batch_op.drop_constraint('fk_payment_receiver', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['id'])
        batch_op.alter_column('amount',
                              existing_type=sa.FLOAT(),
                              nullable=True)
        batch_op.drop_column('booking_id')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_start', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.DATE(), nullable=True))

    op.create_table(
        '_alembic_tmp_car',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('make', sa.VARCHAR(length=50), nullable=False),
        sa.Column('model', sa.VARCHAR(length=50), nullable=False),
        sa.Column('year', sa.INTEGER(), nullable=False),
        sa.Column('price_per_day', sa.FLOAT(), nullable=False),
        sa.Column('available', sa.BOOLEAN(), nullable=True),
        sa.Column('owner_id', sa.INTEGER(), nullable=False),
        sa.Column('location', sa.VARCHAR(length=100), server_default=sa.text("'Unknown'"), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
